window.family_values = {
    "avalon": "挑戰節 I - 阿瓦隆",
    "corellia": "挑戰節 I - 海盜",
    "grimforest": "挑戰節 I - 肅煞森林",
    "guardiansteltoc": "挑戰節 I - 守護者",
    "wonderland": "挑戰節 I - 仙境",
    "villains": "挑戰節 II - 惡棍",
    "starfall": "挑戰節 II - 星隕",
    "slayer": "挑戰節 II - 殺手",
    "wolf": "聯盟 - 惡狼",
    "raven": "聯盟 - 渡鴉",
    "springvale": "月活動 - 斯普林維爾",
    "sand": "月活動 - 飛沙帝國",
    "morlovia": "月活動 - 莫洛維亞",
    "christmas": "月活動 - 冬季",
    "ninja": "高塔 - 忍者",
    "magic": "高塔 - 魔法",
    "lagoon": "S2 - 環礁湖",
    "sakura": "S2 - 櫻花",
    "atlantis": "S2 - 亞特蘭蒂斯",
    "alfheim": "S3 - 亞爾夫海姆",
    "asgard": "S3 - 阿斯嘉",
    "helheim": "S3 - 冥界",
    "jotunheim": "S3 - 約頓海姆",
    "midgard": "S3 - 密德嘉",
    "muspelheim": "S3 - 穆斯貝爾海姆",
    "niflheim": "S3 - 尼弗爾海姆",
    "svartalfheim": "S3 - 斯瓦塔爾法海姆",
    "vanaheim": "S3 - 華納海姆",
    "underwild": "S4 - 地底荒野",
    "kingdom": "三國 - 王國",
    "sun": "S5 - 烈日",
    "moon": "S5 - 明月",
    "gargoyle": "挑戰 - 石像鬼",
    "styx": "高塔 - 冥河",
    "kalevala": "月活動 - 卡勒瓦拉",
    "bard": "挑戰節 II - 吟遊詩人",
    "plainshunter": "怪物島 - 平原獵人",
    "superelemental": "超級元素",
    "pets": "挑戰節 II - 強大寵物",
    "masquerade": "挑戰 - 化裝舞會",
    "musketeer": "聯盟 - 火槍手",
    "classic": "S1 - 經典",
    "lunaryear": "月活動 - 農曆新年",
    "cupid": "月活動 - 邱比特",
    "journey": "三國 - 旅程",
    "junglehunter": "怪物島 - 叢林獵人",
    "abysshunter": "怪物島 - 深淵獵人",
    "defendersofatlantis": "S6 - 亞特蘭蒂斯衛士",
    "nightmaresofatlantis": "S6 - 亞特蘭蒂斯的夢魘",
    "beachparty": "月活動 - 海灘派對",
    "construct": "構造體",
    "opera": "挑戰 - 歌劇",
    "maskedgod": "挑戰 - 蒙面之神",
    "goblin": "哥布林",
    "stag": "聯盟 - 雄鹿",
    "bear": "聯盟 - 熊",
    "astralelves": "星界巫師",
    "champions": "酒館 - 勇士",
    "owl": "高塔 - 貓頭鷹",
    "investigator": "神秘 - 調查者",
    "garrisonguard": "衛戍守衛",
    "cultist": "神秘 - 邪教徒",
    "slime": "史萊姆",
    "fox": "狐狸",
    "woodlandfaun": "林地 - 木地羊人",
    "mystery": "神秘",
    "beowulf": "挑戰 - 貝武夫",
    "nidavellir": "S7 - 尼達維爾",
    "astraldwarfs": "星界矮人",
    "moth": "聯盟 - 飛蛾",
    "wildcat": "野貓",
    "myrkheim": "S7 - 米爾克海姆",
    "magiccarpet": "高塔 - 魔毯",
    "mimic": "模仿怪",
    "outlaws": "三國 - 梁山好漢",
    "mahayoddha": "瑪哈悠達", 
    "2017": "月英 - 2017",
    "2018": "月英 - 2018",
    "2019": "月英 - 2019",
    "2020": "月英 - 2020",
    "2021": "月英 - 2021",
    "2022": "月英 - 2022",
    "2023": "月英 - 2023",
    "2024": "月英 - 2024",
    "2025": "月英 - 2025"
};