window.family_values = {
    "knight": "挑战节 I - 阿瓦隆",
    "pirate": "挑战节 I - 海盗",
    "fable": "挑战节 I - 肃煞森林",
    "guardian": "挑战节 I - 守护者",
    "wonderland": "挑战节 I - 仙境",
    "villains": "挑战节 II - 恶棍",
    "circus": "挑战节 II - 星落",
    "slayers": "挑战节 II - 杀手",
    "wolf": "联盟 - 恶狼",
    "raven": "联盟 - 渡鸦",
    "easter": "月活动 - 春谷",
    "sand": "月活动 - 飞沙帝国",
    "halloween": "月活动 - 莫洛维亚",
    "fleur_de_sang": "月活动 - 弗勒德桑",
    "winter": "月活动 - 冬日",
    "ninja": "高塔 - 忍者",
    "magic": "高塔 - 魔法",
    "lagoon": "S2 - 环礁湖",
    "japanese": "S2 - 樱花",
    "atlantis": "S2 - 亚特兰蒂斯",
    "alfheim": "S3 - 艾尔夫海姆",
    "asgard": "S3 - 阿斯加德",
    "helheim": "S3 - 海姆冥界",
    "jotunheim": "S3 - 约顿海姆",
    "midgard": "S3 - 米德加德",
    "muspelheim": "S3 - 穆斯贝尔海姆",
    "niflheim": "S3 - 尼福尔海姆",
    "svartalfheim": "S3 - 瓦特海姆",
    "vanaheim": "S3 - 瓦纳海姆",
    "abyss": "S4 - 蛮荒地界",
    "kingdom": "三国 - 三国",
    "sun": "S5 - 太阳",
    "moon": "S5 - 月亮",
    "gargoyle": "挑战 - 石像鬼",
    "styx": "高塔 - 冥河",
    "kalevala": "月活动 - 卡勒瓦拉",
    "bard": "挑战节 II - 吟游诗人",
    "plains_hunter": "怪兽岛 - 平原猎人",
    "super_elemental": "超级元素 - 超级元素人",
    "mighty_pet": "挑战节 II - 超能萌宠",
    "masquerade": "挑战 - 化装舞会",
    "musketeer": "联盟 - 火枪手",
    "classic": "S1 - 经典",
    "zodiac": "月活动 - 农历生肖",
    "cupid": "月活动 - 爱神",
    "journey": "三国 - 西游",
    "jungle_hunter": "怪兽岛 - 丛林猎人",
    "abyss_hunter": "怪兽岛 - 深渊猎人",
    "tales1_goodies": "S6 - 亚特兰蒂斯卫士",
    "tales1_baddies": "S6 - 亚特兰蒂斯梦魇",
    "beachparty": "月活动 - 海滩派对",
    "construct": "机械",
    "opera": "挑战 - 歌剧",
    "maskedgod": "挑战 - 蒙面之神",
    "goblin": "哥布林村 - 哥布林",
    "stag": "联盟 - 雄鹿",
    "bear": "联盟 - 野熊",
    "astral_elves": "星体精灵 - 星体精灵",
    "astral_demons": "星体精灵 - 星体恶魔",
    "champions": "酒馆 - 冠军",
    "owl": "高塔 - 猫头鹰",
    "investigator": "暗影 - 调查员",
    "cultist": "暗影 - 异教徒",
    "forsaken": "暗影 - 被遗弃者",
    "institute": "暗影 - 学院",
    "garrison": "哥布林村 - 驻军守卫",
    "slime": "超级元素 - 史莱姆",
    "fox": "狐狸",
    "faun": "林地牧神",
    "mystery": "神秘",
    "beowulf": "挑战 - 贝奥武夫",
    "astral_dwarfs": "星体精灵 - 星体矮人",
    "moths": "联盟 - 飞蛾",
    "wild_cat": "野猫",
    "nidavellir": "S7 - 尼达维利尔",
    "myrkheim": "S7 - 马克海姆",
    "magic_carpet": "高塔 - 魔毯",
    "mimic": "拟态兽",
    "outlaw": "三国 - 梁山好汉",
    "mahayoddha":"马哈尤达",
    "vegetable":"英勇植物",
    "hotm2017": "月英 - 2017",
    "hotm2018": "月英 - 2018",
    "hotm2019": "月英 - 2019",
    "hotm2020": "月英 - 2020",
    "hotm2021": "月英 - 2021",
    "hotm2022": "月英 - 2022",
    "hotm2023": "月英 - 2023",
    "hotm2024": "月英 - 2024",
    "hotm2025": "月英 - 2025"
};