window.family_values = {
    "avalon": "Challenge Festival I - Avalon",
    "corellia": "Challenge Festival I - Pirates",
    "grimforest": "Challenge Festival I - Grim Forest",
    "guardiansteltoc": "Challenge Festival I - Guardians",
    "wonderland": "Challenge Festival I - Wonderland",
    "villains": "Challenge Festival II - Villains",
    "starfall": "Challenge Festival II - Starfall",
    "slayer": "Challenge Festival II - Slayers",
    "wolf": "Alliance - Wolves",
    "raven": "Alliance - Ravens",
    "springvale": "Monthly Event - Springvale",
    "sand": "Monthly Event - Sand Empire",
    "morlovia": "Monthly Event - Morlovia",
    "christmas": "Monthly Event - Winter",
    "ninja": "Tower - Ninjas",
    "magic": "Tower - Magic",
    "lagoon": "S2 - Lagoon",
    "sakura": "S2 - Sakura",
    "atlantis": "S2 - Atlantis",
    "alfheim": "S3 - Alfheim",
    "asgard": "S3 - Asgard",
    "helheim": "S3 - Helheim",
    "jotunheim": "S3 - Jotunheim",
    "midgard": "S3 - Midgard",
    "muspelheim": "S3 - Muspelheim",
    "niflheim": "S3 - Niflheim",
    "svartalfheim": "S3 - Svartalfheim",
    "vanaheim": "S3 - Vanaheim",
    "underwild": "S4 - Underwild",
    "kingdom": "Three Kingdoms - Kingdoms",
    "sun": "S5 - Sun",
    "moon": "S5 - Moon",
    "gargoyle": "Challenge - Gargoyle",
    "styx": "Tower - Styx",
    "kalevala": "Monthly Event - Kalevala",
    "bard": "Challenge Festival II - Bards",
    "plainshunter": "Monster Island - Plains Hunters",
    "superelemental": "Super Elemental - Super Elementals",
    "pets": "Challenge Festival II - Pets",
    "masquerade": "Challenge - Masquerade",
    "musketeer": "Alliance - Musketeers",
    "classic": "S1 - Classic",
    "lunaryear": "Monthly Event - Lunar Year",
    "cupid": "Monthly Event - Cupid",
    "journey": "Three Kingdoms - Journey",
    "junglehunter": "Monster Island - Jungle Hunters",
    "abysshunter": "Monster Island - Abyss Hunters",
    "defendersofatlantis": "S6 - Defenders of Atlantis",
    "nightmaresofatlantis": "S6 - Nightmares of Atlantis",
    "beachparty": "Monthly Event - Beach Party",
    "construct": "Constructs",
    "opera": "Challenge - Opera",
    "maskedgod": "Challenge - Masked God",
    "goblin": "Goblin Village - Goblins",
    "stag": "Alliance - Stags",
    "bear": "Alliance - Bears",
    "astralelves": "Astral Plane - Astral Elves",
    "champions": "Tavern - Champions",
    "owl": "Tower - Owls",
    "investigator": "Mystery - Investigator",
    "garrisonguard": "Goblin Village - Garrison Guards",
    "cultist": "Mystery - Cultists",
    "slime": "Super Elemental - Slimes",
    "fox": "Foxes",
    "woodlandfaun": "Woodland Fauns",
    "mystery": "Mystery",
    "beowulf": "Challenge - Beowulf",
    "nidavellir": "S7 - Nidavellir",
    "astraldwarfs": "Astral Plane - Astral Dwarfs",
    "moth": "Alliance - Moths",
    "wildcat": "Wildcats",
    "myrkheim": "S7 - Myrkheim",
    "magiccarpet": "Tower - Magic Carpet",
    "mimic": "Mimics",
    "outlaws": "Three Kingdoms - Outlaws",
    "mahayoddha": "Mahayoddha",
    "2017": "Monthly Hero - 2017",
    "2018": "Monthly Hero - 2018",
    "2019": "Monthly Hero - 2019",
    "2020": "Monthly Hero - 2020",
    "2021": "Monthly Hero - 2021",
    "2022": "Monthly Hero - 2022",
    "2023": "Monthly Hero - 2023",
    "2024": "Monthly Hero - 2024",
    "2025": "Monthly Hero - 2025"
};