window.family_values = {
    "knight": "Challenge Festival I - Avalon",
    "pirate": "Challenge Festival I - Pirates",
    "fable": "Challenge Festival I - Grim Forest",
    "guardian": "Challenge Festival I - Guardians",
    "wonderland": "Challenge Festival I - Wonderland",
    "villains": "Challenge Festival II - Villains",
    "circus": "Challenge Festival II - Starfall",
    "slayers": "Challenge Festival II - Slayers",
    "wolf": "Alliance - Wolves",
    "raven": "Alliance - Ravens",
    "easter": "Monthly Event - Springvale",
    "sand": "Monthly Event - Sand Empire",
    "halloween": "Monthly Event - Morlovia",
    "fleur_de_sang": "Monthly Event - Fleur de Sang",
    "winter": "Monthly Event - Winter",
    "ninja": "Tower - Ninjas",
    "magic": "Tower - Magic",
    "lagoon": "S2 - Lagoon",
    "japanese": "S2 - Sakura",
    "atlantis": "S2 - Atlantis",
    "alfheim": "S3 - Alfheim",
    "asgard": "S3 - Asgard",
    "helheim": "S3 - Helheim",
    "jotunheim": "S3 - Jotunheim",
    "midgard": "S3 - Midgard",
    "muspelheim": "S3 - Muspelheim",
    "niflheim": "S3 - Niflheim",
    "svartalfheim": "S3 - Svartalfheim",
    "vanaheim": "S3 - Vanaheim",
    "abyss": "S4 - Underwild",
    "kingdom": "Three Kingdoms - Kingdoms",
    "sun": "S5 - Sun",
    "moon": "S5 - Moon",
    "gargoyle": "Challenge - Gargoyle",
    "styx": "Tower - Styx",
    "kalevala": "Monthly Event - Kalevala",
    "bard": "Challenge Festival II - Bards",
    "plains_hunter": "Monster Island - Plains Hunters",
    "super_elemental": "Super Elemental - Super Elementals",
    "mighty_pet": "Challenge Festival II - Pets",
    "masquerade": "Challenge - Masquerade",
    "musketeer": "Alliance - Musketeers",
    "classic": "S1 - Classic",
    "zodiac": "Monthly Event - Lunar Year",
    "cupid": "Monthly Event - Cupid",
    "journey": "Three Kingdoms - Journey",
    "jungle_hunter": "Monster Island - Jungle Hunters",
    "abyss_hunter": "Monster Island - Abyss Hunters",
    "tales1_goodies": "S6 - Defenders of Atlantis",
    "tales1_baddies": "S6 - Nightmares of Atlantis",
    "beachparty": "Monthly Event - Beach Party",
    "construct": "Constructs",
    "opera": "Challenge - Opera",
    "maskedgod": "Challenge - Masked God",
    "goblin": "Goblin Village - Goblins",
    "stag": "Alliance - Stags",
    "bear": "Alliance - Bears",
    "astral_elves": "Astral Plane - Astral Elves",
    "astral_demons": "Astral Plane - Astral Demons",
    "champions": "Tavern - Champions",
    "owl": "Tower - Owls",
    "investigator": "Shadow - Investigator",
    "cultist": "Shadow - Cultists",
    "forsaken": "Shadow - Forsaken",
    "institute": "Shadow - The Institute",
    "garrison": "Goblin Village - Garrison Guards",
    "slime": "Super Elemental - Slimes",
    "fox": "Foxes",
    "faun": "Woodland Fauns",
    "mystery": "Mystery",
    "beowulf": "Challenge - Beowulf",
    "nidavellir": "S7 - Nidavellir",
    "astral_dwarfs": "Astral Plane - Astral Dwarfs",
    "moths": "Alliance - Moths",
    "wild_cat": "Wildcats",
    "myrkheim": "S7 - Myrkheim",
    "magic_carpet": "Tower - Magic Carpet",
    "mimic": "Mimics",
    "outlaw": "Three Kingdoms - Outlaws",
    "mahayoddha": "Mahayoddha",
    "vegetable": "Vegetable",
    "beauty_beast": "Beauty and the Beast",
    "shady_scoundrels": "Shady Scoundrel",
    "hotm2017": "Monthly Hero - 2017",
    "hotm2018": "Monthly Hero - 2018",
    "hotm2019": "Monthly Hero - 2019",
    "hotm2020": "Monthly Hero - 2020",
    "hotm2021": "Monthly Hero - 2021",
    "hotm2022": "Monthly Hero - 2022",
    "hotm2023": "Monthly Hero - 2023",
    "hotm2024": "Monthly Hero - 2024",
    "hotm2025": "Monthly Hero - 2025",
    "hotm2025": "Monthly Hero - 2026"
};