window.family_values = {
    "knight": "挑戰節 I - 阿瓦隆",
    "pirate": "挑戰節 I - 海盜",
    "fable": "挑戰節 I - 肅煞森林",
    "guardian": "挑戰節 I - 守護者",
    "wonderland": "挑戰節 I - 仙境",
    "villains": "挑戰節 II - 惡棍",
    "circus": "挑戰節 II - 星隕",
    "slayers": "挑戰節 II - 殺手",
    "wolf": "聯盟 - 惡狼",
    "raven": "聯盟 - 渡鴉",
    "easter": "月活動 - 斯普林維爾",
    "sand": "月活動 - 飛沙帝國",
    "halloween": "月活動 - 莫洛維亞",
    "fleur_de_sang": "月活動 - 血花",
    "winter": "月活動 - 冬季",
    "ninja": "高塔 - 忍者",
    "magic": "高塔 - 魔法",
    "lagoon": "S2 - 環礁湖",
    "japanese": "S2 - 櫻花",
    "atlantis": "S2 - 亞特蘭蒂斯",
    "alfheim": "S3 - 亞爾夫海姆",
    "asgard": "S3 - 阿斯嘉",
    "helheim": "S3 - 冥界",
    "jotunheim": "S3 - 約頓海姆",
    "midgard": "S3 - 密德嘉",
    "muspelheim": "S3 - 穆斯貝爾海姆",
    "niflheim": "S3 - 尼弗爾海姆",
    "svartalfheim": "S3 - 斯瓦塔爾法海姆",
    "vanaheim": "S3 - 華納海姆",
    "abyss": "S4 - 地底荒野",
    "kingdom": "三國 - 王國",
    "sun": "S5 - 烈日",
    "moon": "S5 - 明月",
    "gargoyle": "挑戰 - 石像鬼",
    "styx": "高塔 - 冥河",
    "kalevala": "月活動 - 卡勒瓦拉",
    "bard": "挑戰節 II - 吟遊詩人",
    "plains_hunter": "怪獸島 - 平原獵人",
    "super_elemental": "超級元素 - 超級元素人",
    "mighty_pet": "挑戰節 II - 強大寵物",
    "masquerade": "挑戰 - 化裝舞會",
    "musketeer": "聯盟 - 火槍手",
    "classic": "S1 - 經典",
    "zodiac": "月活動 - 農曆新年",
    "cupid": "月活動 - 邱比特",
    "journey": "三國 - 旅程",
    "jungle_hunter": "怪獸島 - 叢林獵人",
    "abyss_hunter": "怪獸島 - 深淵獵人",
    "tales1_goodies": "S6 - 亞特蘭蒂斯衛士",
    "tales1_baddies": "S6 - 亞特蘭蒂斯的夢魘",
    "beachparty": "月活動 - 海灘派對",
    "construct": "聖約召喚 - 構造體",
    "opera": "挑戰 - 歌劇",
    "maskedgod": "挑戰 - 蒙面之神",
    "goblin": "哥布林村 - 哥布林",
    "stag": "聯盟 - 雄鹿",
    "bear": "聯盟 - 熊",
    "astral_elves": "星界巫師 - 星界巫師",
    "astral_demons": "星界巫師 - 星界惡魔",
    "champions": "酒館 - 勇士",
    "owl": "高塔 - 貓頭鷹",
    "investigator": "暗影 - 調查者",
    "cultist": "暗影 - 邪教徒",
    "forsaken": "暗影 - 遺棄",
    "institute": "暗影 - 學院",
    "garrison": "哥布林村 - 衛戍守衛",
    "slime": "超級元素 - 史萊姆",
    "fox": "聖約召喚 - 狐狸",
    "faun": "野地召喚 - 木地羊人",
    "mystery": "神秘",
    "beowulf": "挑戰 - 貝武夫",
    "nidavellir": "S7 - 尼達維爾",
    "astral_dwarfs": "星界巫師 - 星界矮人",
    "moths": "聯盟 - 飛蛾",
    "wild_cat": "野地召喚 - 野貓",
    "myrkheim": "S7 - 米爾克海姆",
    "magic_carpet": "高塔 - 魔毯",
    "mimic": "模仿怪",
    "outlaw": "三國 - 梁山好漢",
    "mahayoddha": "瑪哈悠達", 
    "vegetable": "蔬菜",
    "beauty_beast": "聯盟 - 美女與野獸",
    "shady_scoundrels": "陰險無賴",
    "titan_hunter": "泰坦獵人召喚 - 泰坦獵人",

    "hotm2017": "月英 - 2017",
    "hotm2018": "月英 - 2018",
    "hotm2019": "月英 - 2019",
    "hotm2020": "月英 - 2020",
    "hotm2021": "月英 - 2021",
    "hotm2022": "月英 - 2022",
    "hotm2023": "月英 - 2023",
    "hotm2024": "月英 - 2024",
    "hotm2025": "月英 - 2025"
};