const classReverseMap = {
  "بربريّ": "barbarian",
  "إكليركي": "cleric",
  "كاهن": "druid",
  "مقاتل": "fighter",
  "راهب": "monk",
  "بالادن": "paladin",
  "حارس جوال": "ranger",
  "محتال": "rogue",
  "مشعوذ": "sorcerer",
  "ساحر": "wizard",
  "野人": "barbarian",
  "牧师": "cleric",
  "德鲁伊": "druid",
  "战士": "fighter",
  "僧侣": "monk",
  "圣骑士": "paladin",
  "游侠": "ranger",
  "盗贼": "rogue",
  "术士": "sorcerer",
  "巫师": "wizard",
  "牧師": "cleric",
  "德魯伊": "druid",
  "戰士": "fighter",
  "僧侶": "monk",
  "騎士": "paladin",
  "遊俠": "ranger",
  "盜賊": "rogue",
  "術士": "sorcerer",
  "巫師": "wizard",
  "barbar": "barbarian",
  "gejstlig": "cleric",
  "druide": "druid",
  "kriger": "fighter",
  "munk": "monk",
  "paladin": "paladin",
  "vandringsmand": "ranger",
  "rebel": "rogue",
  "heksemester": "sorcerer",
  "troldmand": "wizard",
  "barbaar": "barbarian",
  "priester": "cleric",
  "druïde": "druid",
  "krijger": "fighter",
  "monnik": "monk",
  "paladijn": "paladin",
  "boogschutter": "ranger",
  "dief": "rogue",
  "tovenaar": "sorcerer",
  "magiër": "wizard",
  "barbarian": "barbarian",
  "cleric": "cleric",
  "druid": "druid",
  "fighter": "fighter",
  "monk": "monk",
  "ranger": "ranger",
  "rogue": "rogue",
  "sorcerer": "sorcerer",
  "wizard": "wizard",
  "barbaari": "barbarian",
  "pappi": "cleric",
  "druidi": "druid",
  "taistelija": "fighter",
  "munkki": "monk",
  "paladiini": "paladin",
  "samooja": "ranger",
  "vaeltaja": "rogue",
  "noita": "sorcerer",
  "velho": "wizard",
  "barbare": "barbarian",
  "ecclésiastique": "cleric",
  "combattant": "fighter",
  "moine": "monk",
  "voyou": "rogue",
  "sorcier": "sorcerer",
  "magicien": "wizard",
  "kleriker": "cleric",
  "kämpfer": "fighter",
  "mönch": "monk",
  "waldläufer": "ranger",
  "schurke": "rogue",
  "zauberer": "sorcerer",
  "magier": "wizard",
  "padri": "cleric",
  "klenik": "druid",
  "petarung": "fighter",
  "petapa": "monk",
  "kesatria": "paladin",
  "pamong": "ranger",
  "berandal": "rogue",
  "penyihir": "sorcerer",
  "dukun": "wizard",
  "barbaro": "barbarian",
  "chierico": "cleric",
  "druido": "druid",
  "combattente": "fighter",
  "monaco": "monk",
  "paladino": "paladin",
  "furfante": "rogue",
  "incantatore": "sorcerer",
  "stregone": "wizard",
  "バーバリアン": "barbarian",
  "ドルイド": "druid",
  "戦士": "fighter",
  "モンク": "monk",
  "パラディン": "paladin",
  "レンジャー": "ranger",
  "ローグ": "rogue",
  "魔術師": "sorcerer",
  "ウィザード": "wizard",
  "야만전사": "barbarian",
  "성직자": "cleric",
  "드루이드": "druid",
  "전투사": "fighter",
  "수도승": "monk",
  "성전사": "paladin",
  "레인저": "ranger",
  "도적": "rogue",
  "마술사": "sorcerer",
  "마법사": "wizard",
  "prest": "cleric",
  "ridder": "paladin",
  "skogvokter": "ranger",
  "tyv": "rogue",
  "magiker": "sorcerer",
  "trollmann": "wizard",
  "barbarzyńca": "barbarian",
  "kleryk": "cleric",
  "wojownik": "fighter",
  "mnich": "monk",
  "paladyn": "paladin",
  "strażnik lasu": "ranger",
  "łotrzyk": "rogue",
  "czarodziej": "sorcerer",
  "czarnoksiężnik": "wizard",
  "bárbaro": "barbarian",
  "clérigo": "cleric",
  "druida": "druid",
  "guerreiro": "fighter",
  "monge": "monk",
  "patrulheiro": "ranger",
  "ladino": "rogue",
  "feiticeiro": "sorcerer",
  "bruxo": "wizard",
  "варвар": "barbarian",
  "церковник": "cleric",
  "друид": "druid",
  "боец": "fighter",
  "монах": "monk",
  "паладин": "paladin",
  "рейнджер": "ranger",
  "разбойник": "rogue",
  "колдун": "sorcerer",
  "маг": "wizard",
  "luchador": "fighter",
  "monje": "monk",
  "paladín": "paladin",
  "guardabosques": "ranger",
  "rebelde": "rogue",
  "hechicero": "sorcerer",
  "brujo": "wizard",
  "präst": "cleric",
  "kämpe": "fighter",
  "skytt": "ranger",
  "tjuv": "rogue",
  "häxmästare": "sorcerer",
  "trollkarl": "wizard",
  "ruhban": "cleric",
  "rahip": "druid",
  "dövüşçü": "fighter",
  "keşiş": "monk",
  "bekçi": "ranger",
  "düzenbaz": "rogue",
  "büyücü": "sorcerer",
  "sihirbaz": "wizard"
};

const colorReverseMap = {
  "ثلج": "blue",
  "طبيعة": "green",
  "ظلام": "purple",
  "نار": "red",
  "مقدّس": "yellow",
  "冰雪": "blue",
  "自然": "green",
  "暗黑": "purple",
  "烈火": "red",
  "神圣": "yellow",
  "神聖": "yellow",
  "is": "blue",
  "natur": "green",
  "mørk": "purple",
  "ild": "red",
  "hellig": "yellow",
  "ijs": "blue",
  "natuur": "green",
  "duister": "purple",
  "vuur": "red",
  "heilig": "yellow",
  "ice": "blue",
  "nature": "green",
  "dark": "purple",
  "fire": "red",
  "holy": "yellow",
  "jää": "blue",
  "luonto": "green",
  "pimeys": "purple",
  "tuli": "red",
  "pyhä": "yellow",
  "glace": "blue",
  "sombre": "purple",
  "feu": "red",
  "sacré": "yellow",
  "eis": "blue",
  "finster": "purple",
  "feuer": "red",
  "es": "blue",
  "alam": "green",
  "gelap": "purple",
  "api": "red",
  "suci": "yellow",
  "ghiaccio": "blue",
  "natura": "green",
  "oscurità": "purple",
  "fuoco": "red",
  "sacro": "yellow",
  "氷": "blue",
  "闇": "purple",
  "炎": "red",
  "聖": "yellow",
  "얼음": "blue",
  "자연": "green",
  "암흑": "purple",
  "불": "red",
  "신성": "yellow",
  "mørke": "purple",
  "lód": "blue",
  "mrok": "purple",
  "ogień": "red",
  "świętość": "yellow",
  "gelo": "blue",
  "natureza": "green",
  "trevas": "purple",
  "fogo": "red",
  "sagrado": "yellow",
  "лед": "blue",
  "природа": "green",
  "тьма": "purple",
  "огонь": "red",
  "святыня": "yellow",
  "hielo": "blue",
  "naturaleza": "green",
  "oscuridad": "purple",
  "fuego": "red",
  "mörk": "purple",
  "eld": "red",
  "helig": "yellow",
  "buz": "blue",
  "doğa": "green",
  "karanlık": "purple",
  "ateş": "red",
  "kutsal": "yellow"
};

const aether_powerReverseMap = {
  "دفاع الأمراض": "aether_ailment_defense",
  "انعكاس الأمراض": "aether_ailment_reflect",
  "مناعة الأمراض": "aether_ailment_shield",
  "هجوم": "aether_attack",
  "ريجين معزز": "aether_boosted_regen",
  "معقل": "aether_bulwark",
  "تطهير": "aether_cleanse",
  "هجوم مضاد": "aether_counterattack",
  "تقليل الضرر": "aether_damage_reduction",
  "دفاع": "aether_defense",
  "تفادي": "aether_dodge",
  "مقاومة العدو": "aether_fiend_resist",
  "تحمُّل الفارس": "aether_flesh_wound",
  "مجازفة": "aether_gamble",
  "زيادة الشفاء": "aether_heal_increase",
  "تعزيز القوة": "aether_mana_boost",
  "توليد القوة": "aether_mana_generation",
  "مومياء": "aether_mummy",
  "عودة الألم": "aether_pain_return",
  "غضب": "aether_rage",
  "ريجين": "aether_regen",
  "إعادة الإحياء": "aether_revive",
  "درع خاص": "aether_special_armor",
  "تعزيز خاص": "aether_special_boost",
  "استهزاء": "aether_taunt",
  "مصاص دماء": "aether_vampire",
  "状态异常防御": "aether_ailment_defense",
  "状态异常反弹": "aether_ailment_reflect",
  "状态异常免疫": "aether_ailment_shield",
  "攻击提升": "aether_attack",
  "生命恢复加成": "aether_boosted_regen",
  "坚壁": "aether_bulwark",
  "净化": "aether_cleanse",
  "反击": "aether_counterattack",
  "减伤": "aether_damage_reduction",
  "防御提升": "aether_defense",
  "闪避": "aether_dodge",
  "恶魔抵抗": "aether_fiend_resist",
  "骑士之毅": "aether_flesh_wound",
  "气运": "aether_gamble",
  "治疗提升": "aether_heal_increase",
  "法力加成": "aether_mana_boost",
  "法力生成": "aether_mana_generation",
  "木乃伊": "aether_mummy",
  "伤害反弹": "aether_pain_return",
  "怒气": "aether_rage",
  "生命恢复": "aether_regen",
  "复活": "aether_revive",
  "特殊护甲": "aether_special_armor",
  "特殊技能加成": "aether_special_boost",
  "嘲讽": "aether_taunt",
  "吸血": "aether_vampire",
  "異常防禦": "aether_ailment_defense",
  "異常反射": "aether_ailment_reflect",
  "異常免疫": "aether_ailment_shield",
  "攻擊提升": "aether_attack",
  "回復已加成": "aether_boosted_regen",
  "壁壘": "aether_bulwark",
  "淨化": "aether_cleanse",
  "反擊": "aether_counterattack",
  "傷害減少": "aether_damage_reduction",
  "防禦提升": "aether_defense",
  "閃避": "aether_dodge",
  "惡魔抵禦": "aether_fiend_resist",
  "騎士的耐力": "aether_flesh_wound",
  "豪賭": "aether_gamble",
  "治療增加": "aether_heal_increase",
  "法力產出": "aether_mana_generation",
  "疼痛回歸": "aether_pain_return",
  "憤怒": "aether_rage",
  "回復": "aether_regen",
  "復活": "aether_revive",
  "特殊盔甲": "aether_special_armor",
  "特殊加成": "aether_special_boost",
  "嘲諷": "aether_taunt",
  "吸血鬼": "aether_vampire",
  "lidelsesforsvar": "aether_ailment_defense",
  "lidelsesrefleksion": "aether_ailment_reflect",
  "lidelsesimmunitet": "aether_ailment_shield",
  "angreb op": "aether_attack",
  "boostet gendannelse": "aether_boosted_regen",
  "bolværk": "aether_bulwark",
  "fjernelse": "aether_cleanse",
  "modangreb": "aether_counterattack",
  "skadereduktion": "aether_damage_reduction",
  "forsvar op": "aether_defense",
  "undgå": "aether_dodge",
  "djævlemodstand": "aether_fiend_resist",
  "ridderens udholdenhed": "aether_flesh_wound",
  "hasard": "aether_gamble",
  "helbredelsesforøgelse": "aether_heal_increase",
  "manaboost": "aether_mana_boost",
  "managendannelse": "aether_mana_generation",
  "mumie": "aether_mummy",
  "retursmerte": "aether_pain_return",
  "raseri": "aether_rage",
  "gendannelse": "aether_regen",
  "genopliv": "aether_revive",
  "særlig rustning": "aether_special_armor",
  "særlig boost": "aether_special_boost",
  "håne": "aether_taunt",
  "vampyr": "aether_vampire",
  "verdediging tegen aandoeningen": "aether_ailment_defense",
  "terugkaatsing van aandoeningen": "aether_ailment_reflect",
  "immuniteit voor aandoeningen": "aether_ailment_shield",
  "meer aanval": "aether_attack",
  "regeneratieboost": "aether_boosted_regen",
  "bolwerk": "aether_bulwark",
  "zuivering": "aether_cleanse",
  "tegenaanval": "aether_counterattack",
  "minder schade": "aether_damage_reduction",
  "meer verdediging": "aether_defense",
  "ontwijken": "aether_dodge",
  "weerstand tegen demonen": "aether_fiend_resist",
  "uithoudingsvermogen van een ridder": "aether_flesh_wound",
  "gokken": "aether_gamble",
  "meer genezing": "aether_heal_increase",
  "manarecuperatie": "aether_mana_generation",
  "mummie": "aether_mummy",
  "pijnomkeer": "aether_pain_return",
  "woede": "aether_rage",
  "regeneratie": "aether_regen",
  "terugkeren": "aether_revive",
  "speciaal harnas": "aether_special_armor",
  "speciaalboost": "aether_special_boost",
  "uitlokken": "aether_taunt",
  "vampier": "aether_vampire",
  "ailment defense": "aether_ailment_defense",
  "ailment reflect": "aether_ailment_reflect",
  "ailment immunity": "aether_ailment_shield",
  "attack up": "aether_attack",
  "boosted regen": "aether_boosted_regen",
  "bulwark": "aether_bulwark",
  "cleanse": "aether_cleanse",
  "counterattack": "aether_counterattack",
  "damage reduction": "aether_damage_reduction",
  "defense up": "aether_defense",
  "dodge": "aether_dodge",
  "fiend resist": "aether_fiend_resist",
  "knight's endurance": "aether_flesh_wound",
  "gamble": "aether_gamble",
  "heal increase": "aether_heal_increase",
  "mana boost": "aether_mana_boost",
  "mana generation": "aether_mana_generation",
  "mummy": "aether_mummy",
  "pain return": "aether_pain_return",
  "rage": "aether_rage",
  "regen": "aether_regen",
  "revive": "aether_revive",
  "special armor": "aether_special_armor",
  "special boost": "aether_special_boost",
  "taunt": "aether_taunt",
  "vampire": "aether_vampire",
  "vaivasuoja": "aether_ailment_defense",
  "vaivojen heijastus": "aether_ailment_reflect",
  "vaivaimmuniteetti": "aether_ailment_shield",
  "hyökkäyslisä": "aether_attack",
  "tehostettu paraneminen": "aether_boosted_regen",
  "suojaus": "aether_bulwark",
  "puhdistus": "aether_cleanse",
  "vastahyökkäys": "aether_counterattack",
  "vaurion vähennys": "aether_damage_reduction",
  "puolustuslisä": "aether_defense",
  "väistö": "aether_dodge",
  "riiviöiden vastustus": "aether_fiend_resist",
  "ritarin kestävyys": "aether_flesh_wound",
  "uhkapeliä": "aether_gamble",
  "parannuslisä": "aether_heal_increase",
  "manatehostus": "aether_mana_boost",
  "manatuotanto": "aether_mana_generation",
  "muumio": "aether_mummy",
  "tuskan palautus": "aether_pain_return",
  "raivo": "aether_rage",
  "paraneminen": "aether_regen",
  "elvytys": "aether_revive",
  "erikoishaarniska": "aether_special_armor",
  "erikoistehostus": "aether_special_boost",
  "piikittely": "aether_taunt",
  "vampyyri": "aether_vampire",
  "défense contre les statuts": "aether_ailment_defense",
  "renvoi des statuts": "aether_ailment_reflect",
  "immunité aux statuts": "aether_ailment_shield",
  "augmentation d'attaque": "aether_attack",
  "régénération boostée": "aether_boosted_regen",
  "rempart": "aether_bulwark",
  "purification": "aether_cleanse",
  "contreattaque": "aether_counterattack",
  "réduction de dégâts": "aether_damage_reduction",
  "augmentation de défense": "aether_defense",
  "esquiver": "aether_dodge",
  "résistance aux démons": "aether_fiend_resist",
  "endurance de chevalier": "aether_flesh_wound",
  "pari": "aether_gamble",
  "augmentation de soin": "aether_heal_increase",
  "boost de mana": "aether_mana_boost",
  "génération de mana": "aether_mana_generation",
  "momie": "aether_mummy",
  "renvoi de la douleur": "aether_pain_return",
  "régénération": "aether_regen",
  "ressusciter": "aether_revive",
  "armure spéciale": "aether_special_armor",
  "boost spécial": "aether_special_boost",
  "provoquer": "aether_taunt",
  "änderungsabwehr": "aether_ailment_defense",
  "änderungsreflexion": "aether_ailment_reflect",
  "änderungsimmunität": "aether_ailment_shield",
  "angriff verstärkt": "aether_attack",
  "verstärkte regeneration": "aether_boosted_regen",
  "bollwerk": "aether_bulwark",
  "reinigen": "aether_cleanse",
  "gegenangriff": "aether_counterattack",
  "schadensreduzierung": "aether_damage_reduction",
  "verteidigung verstärkt": "aether_defense",
  "ausweichen": "aether_dodge",
  "feindresistenz": "aether_fiend_resist",
  "ausdauer eines ritters": "aether_flesh_wound",
  "glücksspiel": "aether_gamble",
  "heilungsverbesserung": "aether_heal_increase",
  "mana-boost": "aether_mana_boost",
  "manaregeneration": "aether_mana_generation",
  "schmerz-rückkehr": "aether_pain_return",
  "wut": "aether_rage",
  "regeneration": "aether_regen",
  "wiederbeleben": "aether_revive",
  "spezialrüstung": "aether_special_armor",
  "spezial-boost": "aether_special_boost",
  "verspotten": "aether_taunt",
  "vampir": "aether_vampire",
  "pertahanan pelemahan": "aether_ailment_defense",
  "pemantulan pelemahan": "aether_ailment_reflect",
  "kekebalan pelemahan": "aether_ailment_shield",
  "serangan naik": "aether_attack",
  "peningkatan regenerasi": "aether_boosted_regen",
  "bersihkan": "aether_cleanse",
  "tangkisserangan": "aether_counterattack",
  "pengurangan kerusakan": "aether_damage_reduction",
  "pertahanan naik": "aether_defense",
  "kelit": "aether_dodge",
  "tampik iblis": "aether_fiend_resist",
  "ketahanan kesatria": "aether_flesh_wound",
  "bertaruh": "aether_gamble",
  "tambah sembuh": "aether_heal_increase",
  "peningkatan mana": "aether_mana_boost",
  "generasi mana": "aether_mana_generation",
  "mumi": "aether_mummy",
  "sakit lagi": "aether_pain_return",
  "kemarahan": "aether_rage",
  "regenerasi": "aether_regen",
  "bangkit": "aether_revive",
  "zirah khusus": "aether_special_armor",
  "peningkatan khusus": "aether_special_boost",
  "ejek": "aether_taunt",
  "difesa dai disturbi": "aether_ailment_defense",
  "riflesso dei disturbi": "aether_ailment_reflect",
  "immunità dai disturbi": "aether_ailment_shield",
  "attacco potenziato": "aether_attack",
  "rigenerazione potenziata": "aether_boosted_regen",
  "baluardo": "aether_bulwark",
  "annullamento": "aether_cleanse",
  "contrattacco": "aether_counterattack",
  "riduzione dei danni": "aether_damage_reduction",
  "difesa potenziata": "aether_defense",
  "schiva": "aether_dodge",
  "resistenza ai demoni": "aether_fiend_resist",
  "resistenza del cavaliere": "aether_flesh_wound",
  "azzardo": "aether_gamble",
  "aumento della guarigione": "aether_heal_increase",
  "potenziamento mana": "aether_mana_boost",
  "rigenerazione mana": "aether_mana_generation",
  "mummia": "aether_mummy",
  "restituzione del dolore": "aether_pain_return",
  "rabbia": "aether_rage",
  "rigenerazione": "aether_regen",
  "rianima": "aether_revive",
  "armatura speciale": "aether_special_armor",
  "potenziamento speciale": "aether_special_boost",
  "deridi": "aether_taunt",
  "vampiro": "aether_vampire",
  "防御異常": "aether_ailment_defense",
  "異常無効化": "aether_ailment_shield",
  "攻撃力増加": "aether_attack",
  "ブースト回復": "aether_boosted_regen",
  "砦": "aether_bulwark",
  "浄化": "aether_cleanse",
  "カウンターアタック": "aether_counterattack",
  "ダメージ軽減": "aether_damage_reduction",
  "防御力増加": "aether_defense",
  "回避": "aether_dodge",
  "フィエンド耐性": "aether_fiend_resist",
  "騎士の忍耐": "aether_flesh_wound",
  "賭け": "aether_gamble",
  "回復量増加": "aether_heal_increase",
  "マナブースト": "aether_mana_boost",
  "マナ生成": "aether_mana_generation",
  "ミイラ": "aether_mummy",
  "痛み返し": "aether_pain_return",
  "怒り": "aether_rage",
  "スキル防御": "aether_special_armor",
  "スキルブースト": "aether_special_boost",
  "挑発": "aether_taunt",
  "상태 이상 방어력": "aether_ailment_defense",
  "상태 이상 반사": "aether_ailment_reflect",
  "상태 이상 면역": "aether_ailment_shield",
  "공격력 증가": "aether_attack",
  "증폭된 재생산": "aether_boosted_regen",
  "방어벽": "aether_bulwark",
  "정화": "aether_cleanse",
  "반격": "aether_counterattack",
  "피해 감소": "aether_damage_reduction",
  "방어력 증가": "aether_defense",
  "회피": "aether_dodge",
  "악마 저항": "aether_fiend_resist",
  "기사의 인내심": "aether_flesh_wound",
  "도박": "aether_gamble",
  "회복력 증가": "aether_heal_increase",
  "마나 증폭": "aether_mana_boost",
  "마나 생산력": "aether_mana_generation",
  "미라": "aether_mummy",
  "통증 재발": "aether_pain_return",
  "분노": "aether_rage",
  "재생산": "aether_regen",
  "부활": "aether_revive",
  "특별 갑옷": "aether_special_armor",
  "특별 부스트": "aether_special_boost",
  "도발": "aether_taunt",
  "뱀파이어": "aether_vampire",
  "lidelseforsvar": "aether_ailment_defense",
  "lidelserefleksjon": "aether_ailment_reflect",
  "lidelseimmunitet": "aether_ailment_shield",
  "angrep opp": "aether_attack",
  "økt regenerasjon": "aether_boosted_regen",
  "beskyttelsesmur": "aether_bulwark",
  "rens": "aether_cleanse",
  "motangrep": "aether_counterattack",
  "skadereduksjon": "aether_damage_reduction",
  "forsvar opp": "aether_defense",
  "dukk": "aether_dodge",
  "motstå undersått": "aether_fiend_resist",
  "ridders utholdenhet": "aether_flesh_wound",
  "gambling": "aether_gamble",
  "økt helse": "aether_heal_increase",
  "økt mana": "aether_mana_boost",
  "mana-generering": "aether_mana_generation",
  "smerteretur": "aether_pain_return",
  "sinne": "aether_rage",
  "regenerasjon": "aether_regen",
  "gjenoppliv": "aether_revive",
  "spesill rustning": "aether_special_armor",
  "spesialøkning": "aether_special_boost",
  "provoser": "aether_taunt",
  "obrona przed dolegliwością": "aether_ailment_defense",
  "odbicie dolegliwości": "aether_ailment_reflect",
  "odporność na dolegliwość": "aether_ailment_shield",
  "wzrost ataku": "aether_attack",
  "zwiększona regeneracja": "aether_boosted_regen",
  "bastion": "aether_bulwark",
  "oczyszczenie": "aether_cleanse",
  "kontratak": "aether_counterattack",
  "zmniejszenie obrażeń": "aether_damage_reduction",
  "zwiększona obrona": "aether_defense",
  "unik": "aether_dodge",
  "odporność na potwory": "aether_fiend_resist",
  "rycerska wytrzymałość": "aether_flesh_wound",
  "hazard": "aether_gamble",
  "zwiększone leczenie": "aether_heal_increase",
  "premia do many": "aether_mana_boost",
  "generowanie many": "aether_mana_generation",
  "mumia": "aether_mummy",
  "odbijanie obrażeń": "aether_pain_return",
  "furia": "aether_rage",
  "regeneracja": "aether_regen",
  "odrodzenie": "aether_revive",
  "specjalny pancerz": "aether_special_armor",
  "wzmocnienie umiejętności specjalnej": "aether_special_boost",
  "prowokacja": "aether_taunt",
  "wampiryzm": "aether_vampire",
  "defesa de males": "aether_ailment_defense",
  "reflexão de males": "aether_ailment_reflect",
  "imunidade a males": "aether_ailment_shield",
  "ataque extra": "aether_attack",
  "regeneração reforçada": "aether_boosted_regen",
  "baluarte": "aether_bulwark",
  "limpeza": "aether_cleanse",
  "contraataque": "aether_counterattack",
  "redução de dano": "aether_damage_reduction",
  "defesa extra": "aether_defense",
  "desviar": "aether_dodge",
  "resistência a demônios": "aether_fiend_resist",
  "resistência do cavaleiro": "aether_flesh_wound",
  "aposta": "aether_gamble",
  "aumento de cura": "aether_heal_increase",
  "reforço de mana": "aether_mana_boost",
  "geração de mana": "aether_mana_generation",
  "múmia": "aether_mummy",
  "devolve dor": "aether_pain_return",
  "fúria": "aether_rage",
  "regeneração": "aether_regen",
  "reviver": "aether_revive",
  "armadura especial": "aether_special_armor",
  "reforço especial": "aether_special_boost",
  "provocar": "aether_taunt",
  "защита от недугов": "aether_ailment_defense",
  "отражение недугов": "aether_ailment_reflect",
  "иммунитет к недугам": "aether_ailment_shield",
  "повышение атаки": "aether_attack",
  "улучшенное восстановление": "aether_boosted_regen",
  "бастион": "aether_bulwark",
  "очищение": "aether_cleanse",
  "контратака": "aether_counterattack",
  "снижение урона": "aether_damage_reduction",
  "повышение защиты": "aether_defense",
  "уклонение": "aether_dodge",
  "сопротивление паразитам": "aether_fiend_resist",
  "рыцарская стойкость": "aether_flesh_wound",
  "риск": "aether_gamble",
  "повышение исцеления": "aether_heal_increase",
  "прибавка маны": "aether_mana_boost",
  "восстановление маны": "aether_mana_generation",
  "мумия": "aether_mummy",
  "возвращение боли": "aether_pain_return",
  "ярость": "aether_rage",
  "регенерация": "aether_regen",
  "возрождение": "aether_revive",
  "особая броня": "aether_special_armor",
  "особое усиление": "aether_special_boost",
  "насмешка": "aether_taunt",
  "вампир": "aether_vampire",
  "defensa contra alteraciones": "aether_ailment_defense",
  "refleja alteraciones": "aether_ailment_reflect",
  "inmunidad frente a alteraciones": "aether_ailment_shield",
  "aumento de ataque": "aether_attack",
  "regeneración potenciada": "aether_boosted_regen",
  "purificación": "aether_cleanse",
  "contra-ataque": "aether_counterattack",
  "reducción del daño": "aether_damage_reduction",
  "aumento de defensa": "aether_defense",
  "esquivar": "aether_dodge",
  "resistencia a demonios": "aether_fiend_resist",
  "aguante de caballero": "aether_flesh_wound",
  "apuesta": "aether_gamble",
  "aumento de curación": "aether_heal_increase",
  "potenciador de maná": "aether_mana_boost",
  "regeneración de maná": "aether_mana_generation",
  "momia": "aether_mummy",
  "devolución de dolor": "aether_pain_return",
  "rabia": "aether_rage",
  "regeneración": "aether_regen",
  "revivir": "aether_revive",
  "potenciador especial": "aether_special_boost",
  "burla": "aether_taunt",
  "effektförsvar": "aether_ailment_defense",
  "effektreflektion": "aether_ailment_reflect",
  "effektimmunitet": "aether_ailment_shield",
  "attack upp": "aether_attack",
  "boostad regeneration": "aether_boosted_regen",
  "bålverk": "aether_bulwark",
  "rensa": "aether_cleanse",
  "motanfall": "aether_counterattack",
  "skademinskning": "aether_damage_reduction",
  "försvar upp": "aether_defense",
  "undvik": "aether_dodge",
  "odjursmotstånd": "aether_fiend_resist",
  "riddarens uthållighet": "aether_flesh_wound",
  "spela": "aether_gamble",
  "ökad läkning": "aether_heal_increase",
  "manaskapande": "aether_mana_generation",
  "smärta tillbaka": "aether_pain_return",
  "ilska": "aether_rage",
  "återuppliva": "aether_revive",
  "specialrustning": "aether_special_armor",
  "specialboost": "aether_special_boost",
  "hån": "aether_taunt",
  "engel savunma": "aether_ailment_defense",
  "engel yansıtma": "aether_ailment_reflect",
  "engele bağışıklık": "aether_ailment_shield",
  "saldırı artışı": "aether_attack",
  "güçlendirilmiş yenileme": "aether_boosted_regen",
  "siper": "aether_bulwark",
  "arındırma": "aether_cleanse",
  "hasar azaltma": "aether_damage_reduction",
  "savunma artışı": "aether_defense",
  "savuştur": "aether_dodge",
  "canavara direnç": "aether_fiend_resist",
  "şövalyenin mukavemeti": "aether_flesh_wound",
  "riske atma": "aether_gamble",
  "şifa artışı": "aether_heal_increase",
  "mana güçlendirme": "aether_mana_boost",
  "mana üretimi": "aether_mana_generation",
  "mumya": "aether_mummy",
  "acı dönüşü": "aether_pain_return",
  "öfke": "aether_rage",
  "yenileme": "aether_regen",
  "dirilt": "aether_revive",
  "özel zırh": "aether_special_armor",
  "özel güçlendirme": "aether_special_boost",
  "alay et": "aether_taunt"
};