//Loading Hero class
//bonus value on grid icon replaced Math.ceil to Math.floor（round down）= v1.1.4fix
var baseatk = 1000
var basepro = 1000
var basehp = 1000
var greenatk = "+15"
var greenpro = "+18"
var greenhp = "+36"
var greenheal = "+2%"
var greenatkplus = "+3%" + " / +" + Math.floor(baseatk * 0.03)
var greenhpplus = "+3%" + " / +" + Math.floor(basehp * 0.03)
var greenproplus = "+3%" + " / +" + Math.floor(basepro * 0.03)

var greenatkpluslast = "+4%" + " / +" + Math.floor(baseatk * 0.04)
var greenhppluslast = "+4%" + " / +" + Math.floor(basehp * 0.04)
var greenpropluslast = "+4%" + " / +" + Math.floor(basepro * 0.04)
var greencritlast = "+4%"
var greenmanalast = "+4%"
var greenheallast = "+4%"

var purpleatk = "+50"
var purpledef = "+60"
var purplehp = "+50"
var purpleBlank = ""



// var greenhppluscos = "+3%" + " / +" + Math.floor("" * (calcCoslife / 100) + "")
var greencrit = "+2%"
var greenmana = "+2%"
var greenheal = "+2%"

if (acfClass == "ranger") {
    $(".classPagelink").html(rangerLink);
    $(".pos1-1").add(".pot1-1").addClass("ranger", "classpoint")
    $(".pos2-1").add(".pot2-1").addClass("powerup").text(greenatk)
    $(".pos2-2").add(".pot2-2").addClass("protectionup").text(greenpro)
    $(".pos3-1").add(".pot3-1").addClass("protectionup").text(greenpro)
    $(".pos3-2").add(".pot3-2").addClass("hpup").text(greenhp)
    $(".pos4-1").add(".pot4-1").addClass("ranger")
    $(".pos5-1").add(".pot5-1").addClass("hpup").text(greenhp)
    $(".pos5-2").add(".pot5-2").addClass("powerup").text(greenatk)
    $(".pos6-1").add(".pot6-1").addClass("protectionup").text(greenpro)
    $(".pos6-2").add(".pot6-2").addClass("hpup").text(greenhp)
    $(".pos7-1").add(".pot7-1").addClass("ranger")
    $(".pos8-1").add(".pot8-1").addClass("protectionplus").text(greenproplus)
    $(".pos8-2").add(".pot8-2").addClass("manaup").text(greenmana)
    $(".pos9-1").add(".pot9-1").addClass("powerup").text(greenatk)
    $(".pos9-2").add(".pot9-2").addClass("hpup").text(greenhp)
    $(".pos10-1").add(".pot10-1").addClass("powerplus").text(greenatkplus)
    $(".pos11-1").add(".pot11-1").addClass("protectionup").text(greenpro)
    $(".pos11-2").add(".pot11-2").addClass("powerup").text(greenatk)
    $(".pos12-1").add(".pot12-1").addClass("ranger")
    $(".pos13-1").add(".pot13-1").addClass("powerup").text(greenatk)
    $(".pos13-2").add(".pot13-2").addClass("hpup").text(greenhp)
    $(".pos14-1").add(".pot14-1").addClass("hpup").text(greenhp)
    $(".pos14-2").add(".pot14-2").addClass("protectionup").text(greenpro)
    $(".pos15-1").add(".pot15-1").addClass("ranger")
    $(".pos16-1").add(".pot16-1").addClass("protectionup").text(greenpro)
    $(".pos16-2").add(".pot16-2").addClass("hpup").text(greenhp)
    $(".pos17-1").add(".pot17-1").addClass("powerup").text(greenatk)
    $(".pos17-2").add(".pot17-2").addClass("protectionup").text(greenpro)
    $(".pos18-1").add(".pot18-1").addClass("powerup").text(greenatk)
    $(".pos19-1").add(".pot19-1").addClass("hpplus").text(greenhpplus)
    $(".pos19-2").add(".pot19-2").addClass("healup").text(greenheal)
    $(".pos20-1").add(".pot20-1").addClass("critup").text(greencritlast)
    // Master Class ↓
    $(".pos21-1").add(".pot21-1").addClass("masterpowerup").text(purpleatk)
    $(".pos21-2").add(".pot21-2").addClass("masterdefup").text(purpledef)
    $(".pos22-1").add(".pot22-1").addClass("masterpowerup").text(purpleatk)
    $(".pos22-2").add(".pot22-2").addClass("masterdefup").text(purpledef)
    $(".pos23-1").add(".pot23-1").addClass("masterhpup").text(purplehp)
    $(".pos24-1").add(".pot24-1").addClass("masterpowerup").text(purpleatk)
    $(".pos24-2").add(".pot24-2").addClass("masterdefup").text(purpledef)
    $(".pos25-1").add(".pot25-1").addClass("masterhpup").text(purplehp)
    $(".pos26-1").add(".pot26-1").addClass("master_fighter").text(greenatkpluslast)
    // Master Class ↑
} else if (acfClass == "cleric") {
    $(".classPagelink").html(clericLink);
    $(".pos1-1").add(".pot1-1").addClass("cleric", "classpoint")
    $(".pos2-1").add(".pot2-1").addClass("hpup").text(greenhp)
    $(".pos2-2").add(".pot2-2").addClass("protectionup").text(greenpro)
    $(".pos3-1").add(".pot3-1").addClass("protectionup").text(greenpro)
    $(".pos3-2").add(".pot3-2").addClass("powerup").text(greenatk)
    $(".pos4-1").add(".pot4-1").addClass("cleric")
    $(".pos5-1").add(".pot5-1").addClass("powerup").text(greenatk)
    $(".pos5-2").add(".pot5-2").addClass("hpup").text(greenhp)
    $(".pos6-1").add(".pot6-1").addClass("protectionup").text(greenpro)
    $(".pos6-2").add(".pot6-2").addClass("powerup").text(greenatk)
    $(".pos7-1").add(".pot7-1").addClass("cleric")
    $(".pos8-1").add(".pot8-1").addClass("powerplus").text(greenatkplus)
    $(".pos8-2").add(".pot8-2").addClass("protectionplus").text(greenproplus)
    $(".pos9-1").add(".pot9-1").addClass("hpup").text(greenhp)
    $(".pos9-2").add(".pot9-2").addClass("powerup").text(greenatk)
    $(".pos10-1").add(".pot10-1").addClass("hpplus").text(greenhpplus)
    $(".pos11-1").add(".pot11-1").addClass("protectionup")
    $(".pos11-2").add(".pot11-2").addClass("hpup").text(greenhp)
    $(".pos12-1").add(".pot12-1").addClass("cleric")
    $(".pos13-1").add(".pot13-1").addClass("hpup").text(greenhp)
    $(".pos13-2").add(".pot13-2").addClass("powerup").text(greenatk)
    $(".pos14-1").add(".pot14-1").addClass("powerup").text(greenatk)
    $(".pos14-2").add(".pot14-2").addClass("protectionup").text(greenpro)
    $(".pos15-1").add(".pot15-1").addClass("cleric")
    $(".pos16-1").add(".pot16-1").addClass("protectionup").text(greenpro)
    $(".pos16-2").add(".pot16-2").addClass("powerup").text(greenatk)
    $(".pos17-1").add(".pot17-1").addClass("hpup").text(greenhp)
    $(".pos17-2").add(".pot17-2").addClass("protectionup").text(greenpro)
    $(".pos18-1").add(".pot18-1").addClass("hpup").text(greenhp)
    $(".pos19-1").add(".pot19-1").addClass("critup").text(greencrit)
    $(".pos19-2").add(".pot19-2").addClass("manaup").text(greenmana)
    $(".pos20-1").add(".pot20-1").addClass("healup").text(greenheal)
    // Master Class ↓
    $(".pos21-1").add(".pot21-1").addClass("masterpowerup").text(purpleatk)
    $(".pos21-2").add(".pot21-2").addClass("masterdefup").text(purpledef)
    $(".pos22-1").add(".pot22-1").addClass("masterpowerup").text(purpleatk)
    $(".pos22-2").add(".pot22-2").addClass("masterdefup").text(purpledef)
    $(".pos23-1").add(".pot23-1").addClass("masterhpup").text(purplehp)
    $(".pos24-1").add(".pot24-1").addClass("masterpowerup").text(purpleatk)
    $(".pos24-2").add(".pot24-2").addClass("masterdefup").text(purpledef)
    $(".pos25-1").add(".pot25-1").addClass("masterhpup").text(purplehp)
    $(".pos26-1").add(".pot26-1").addClass("master_fighter").text(greenatkpluslast)
    // Master Class ↑

} else if (acfClass == "sorcerer") {
    $(".classPagelink").html(sorcererLink);
    $(".pos1-1").add(".pot1-1").addClass("sorcerer", "classpoint")
    $(".pos2-1").add(".pot2-1").addClass("protectionup").text(greenpro)
    $(".pos2-2").add(".pot2-2").addClass("hpup").text(greenhp)
    $(".pos3-1").add(".pot3-1").addClass("hpup").text(greenhp)
    $(".pos3-2").add(".pot3-2").addClass("powerup").text(greenatk)
    $(".pos4-1").add(".pot4-1").addClass("sorcerer")
    $(".pos5-1").add(".pot5-1").addClass("powerup").text(greenatk)
    $(".pos5-2").add(".pot5-2").addClass("protectionup").text(greenpro)
    $(".pos6-1").add(".pot6-1").addClass("hpup").text(greenhp)
    $(".pos6-2").add(".pot6-2").addClass("powerup").text(greenatk)
    $(".pos7-1").add(".pot7-1").addClass("sorcerer")
    $(".pos8-1").add(".pot8-1").addClass("healup").text(greenheal)
    $(".pos8-2").add(".pot8-2").addClass("critup").text(greencrit)
    $(".pos9-1").add(".pot9-1").addClass("protectionup").text(greenpro)
    $(".pos9-2").add(".pot9-2").addClass("powerup").text(greenatk)
    $(".pos10-1").add(".pot10-1").addClass("hpplus").text(greenhpplus)
    $(".pos11-1").add(".pot11-1").addClass("hpup").text(greenhp)
    $(".pos11-2").add(".pot11-2").addClass("protectionup").text(greenpro)
    $(".pos12-1").add(".pot12-1").addClass("sorcerer")
    $(".pos13-1").add(".pot13-1").addClass("protectionup").text(greenpro)
    $(".pos13-2").add(".pot13-2").addClass("powerup").text(greenatk)
    $(".pos14-1").add(".pot14-1").addClass("powerup").text(greenatk)
    $(".pos14-2").add(".pot14-2").addClass("hpup").text(greenhp)
    $(".pos15-1").add(".pot15-1").addClass("sorcerer")
    $(".pos16-1").add(".pot16-1").addClass("hpup").text(greenhp)
    $(".pos16-2").add(".pot16-2").addClass("powerup").text(greenatk)
    $(".pos17-1").add(".pot17-1").addClass("protectionup").text(greenpro)
    $(".pos17-2").add(".pot17-2").addClass("hpup").text(greenhp)
    $(".pos18-1").add(".pot18-1").addClass("protectionup").text(greenpro)
    $(".pos19-1").add(".pot19-1").addClass("powerplus").text(greenatkplus)
    $(".pos19-2").add(".pot19-2").addClass("protectionplus").text(greenproplus)
    $(".pos20-1").add(".pot20-1").addClass("manaup").text(greenmanalast)
    // Master Class ↓
    $(".pos21-1").add(".pot21-1").addClass("masterpowerup").text(purpleatk)
    $(".pos21-2").add(".pot21-2").addClass("masterdefup").text(purpledef)
    $(".pos22-1").add(".pot22-1").addClass("masterpowerup").text(purpleatk)
    $(".pos22-2").add(".pot22-2").addClass("masterdefup").text(purpledef)
    $(".pos23-1").add(".pot23-1").addClass("masterhpup").text(purplehp)
    $(".pos24-1").add(".pot24-1").addClass("masterpowerup").text(purpleatk)
    $(".pos24-2").add(".pot24-2").addClass("masterdefup").text(purpledef)
    $(".pos25-1").add(".pot25-1").addClass("masterhpup").text(purplehp)
    $(".pos26-1").add(".pot26-1").addClass("master_fighter").text(greenatkpluslast)
    // Master Class ↑
} else if (acfClass == "barbarian") {
    $(".classPagelink").html(barbrianLink);
    $(".pos1-1").add(".pot1-1").addClass("barbarian", "classpoint")
    $(".pos2-1").add(".pot2-1").addClass("powerup").text(greenatk)
    $(".pos2-2").add(".pot2-2").addClass("hpup").text(greenhp)
    $(".pos3-1").add(".pot3-1").addClass("hpup").text(greenhp)
    $(".pos3-2").add(".pot3-2").addClass("protectionup").text(greenpro)
    $(".pos4-1").add(".pot4-1").addClass("barbarian", "classpoint")
    $(".pos5-1").add(".pot5-1").addClass("protectionup").text(greenpro)
    $(".pos5-2").add(".pot5-2").addClass("powerup").text(greenatk)
    $(".pos6-1").add(".pot6-1").addClass("hpup").text(greenhp)
    $(".pos6-2").add(".pot6-2").addClass("protectionup").text(greenpro)
    $(".pos7-1").add(".pot7-1").addClass("barbarian", "classpoint")
    $(".pos8-1").add(".pot8-1").addClass("healup").text(greenheal)
    $(".pos8-2").add(".pot8-2").addClass("powerplus").text(greenatkplus)
    $(".pos9-1").add(".pot9-1").addClass("powerup").text(greenatk)
    $(".pos9-2").add(".pot9-2").addClass("protectionup").text(greenpro)
    $(".pos10-1").add(".pot10-1").addClass("critup").text(greencrit)
    $(".pos11-1").add(".pot11-1").addClass("hpup").text(greenhp)
    $(".pos11-2").add(".pot11-2").addClass("powerup").text(greenatk)
    $(".pos12-1").add(".pot12-1").addClass("barbarian", "classpoint")
    $(".pos13-1").add(".pot13-1").addClass("powerup").text(greenatk)
    $(".pos13-2").add(".pot13-2").addClass("protectionup").text(greenpro)
    $(".pos14-1").add(".pot14-1").addClass("protectionup").text(greenpro)
    $(".pos14-2").add(".pot14-2").addClass("hpup").text(greenhp)
    $(".pos15-1").add(".pot15-1").addClass("barbarian", "classpoint")
    $(".pos16-1").add(".pot16-1").addClass("hpup").text(greenhp)
    $(".pos16-2").add(".pot16-2").addClass("protectionup").text(greenpro)
    $(".pos17-1").add(".pot17-1").addClass("powerup").text(greenatk)
    $(".pos17-2").add(".pot17-2").addClass("hpup").text(greenhp)
    $(".pos18-1").add(".pot18-1").addClass("powerup").text(greenatk)
    $(".pos19-1").add(".pot19-1").addClass("manaup").text(greenmana)
    $(".pos19-2").add(".pot19-2").addClass("protectionplus").text(greenproplus)
    $(".pos20-1").add(".pot20-1").addClass("hpplus").text(greenhppluslast)
    // Master Class ↓
    $(".pos21-1").add(".pot21-1").addClass("masterpowerup").text(purpleatk)
    $(".pos21-2").add(".pot21-2").addClass("masterdefup").text(purpledef)
    $(".pos22-1").add(".pot22-1").addClass("masterpowerup").text(purpleatk)
    $(".pos22-2").add(".pot22-2").addClass("masterdefup").text(purpledef)
    $(".pos23-1").add(".pot23-1").addClass("masterhpup").text(purplehp)
    $(".pos24-1").add(".pot24-1").addClass("masterpowerup").text(purpleatk)
    $(".pos24-2").add(".pot24-2").addClass("masterdefup").text(purpledef)
    $(".pos25-1").add(".pot25-1").addClass("masterhpup").text(purplehp)
    $(".pos26-1").add(".pot26-1").addClass("master_fighter").text(greenatkpluslast)
    // Master Class ↑
} else if (acfClass == "druid") {
    $(".classPagelink").html(druidLink);
    $(".pos1-1").add(".pot1-1").addClass("druid", "classpoint")
    $(".pos2-1").add(".pot2-1").addClass("hpup").text(greenhp)
    $(".pos2-2").add(".pot2-2").addClass("powerup").text(greenatk)
    $(".pos3-1").add(".pot3-1").addClass("powerup").text(greenatk)
    $(".pos3-2").add(".pot3-2").addClass("protectionup").text(greenpro)
    $(".pos4-1").add(".pot4-1").addClass("druid", "classpoint")
    $(".pos5-1").add(".pot5-1").addClass("protectionup").text(greenpro)
    $(".pos5-2").add(".pot5-2").addClass("hpup").text(greenhp)
    $(".pos6-1").add(".pot6-1").addClass("powerup").text(greenatk)
    $(".pos6-2").add(".pot6-2").addClass("protectionup").text(greenpro)
    $(".pos7-1").add(".pot7-1").addClass("druid", "classpoint")
    $(".pos8-1").add(".pot8-1").addClass("healup").text(greenheal)
    $(".pos8-2").add(".pot8-2").addClass("powerplus").text(greenatkplus)
    $(".pos9-1").add(".pot9-1").addClass("hpup").text(greenhp)
    $(".pos9-2").add(".pot9-2").addClass("protectionup").text(greenpro)
    $(".pos10-1").add(".pot10-1").addClass("hpplus").text(greenhpplus)
    $(".pos11-1").add(".pot11-1").addClass("powerup").text(greenatk)
    $(".pos11-2").add(".pot11-2").addClass("hpup").text(greenhp)
    $(".pos12-1").add(".pot12-1").addClass("druid", "classpoint")
    $(".pos13-1").add(".pot13-1").addClass("hpup").text(greenhp)
    $(".pos13-2").add(".pot13-2").addClass("protectionup").text(greenpro)
    $(".pos14-1").add(".pot14-1").addClass("protectionup").text(greenpro)
    $(".pos14-2").add(".pot14-2").addClass("powerup").text(greenatk)
    $(".pos15-1").add(".pot15-1").addClass("druid", "classpoint")
    $(".pos16-1").add(".pot16-1").addClass("powerup").text(greenatk)
    $(".pos16-2").add(".pot16-2").addClass("protectionup").text(greenpro)
    $(".pos17-1").add(".pot17-1").addClass("hpup").text(greenhp)
    $(".pos17-2").add(".pot17-2").addClass("powerup").text(greenatk)
    $(".pos18-1").add(".pot18-1").addClass("hpup").text(greenhp)
    $(".pos19-1").add(".pot19-1").addClass("critup").text(greencrit)
    $(".pos19-2").add(".pot19-2").addClass("protectionplus").text(greenproplus)
    $(".pos20-1").add(".pot20-1").addClass("manaup").text(greenmanalast)
    // Master Class ↓
    $(".pos21-1").add(".pot21-1").addClass("masterpowerup").text(purpleatk)
    $(".pos21-2").add(".pot21-2").addClass("masterdefup").text(purpledef)
    $(".pos22-1").add(".pot22-1").addClass("masterpowerup").text(purpleatk)
    $(".pos22-2").add(".pot22-2").addClass("masterdefup").text(purpledef)
    $(".pos23-1").add(".pot23-1").addClass("masterhpup").text(purplehp)
    $(".pos24-1").add(".pot24-1").addClass("masterpowerup").text(purpleatk)
    $(".pos24-2").add(".pot24-2").addClass("masterdefup").text(purpledef)
    $(".pos25-1").add(".pot25-1").addClass("masterhpup").text(purplehp)
    $(".pos26-1").add(".pot26-1").addClass("master_fighter").text(greenatkpluslast)
    // Master Class ↑
} else if (acfClass == "fighter") {
    $(".classPagelink").html(fighterLink);
    $(".pos1-1").add(".pot1-1").addClass("fighter", "classpoint")
    $(".pos2-1").add(".pot2-1").addClass("protectionup").text(greenpro)
    $(".pos2-2").add(".pot2-2").addClass("powerup").text(greenatk)
    $(".pos3-1").add(".pot3-1").addClass("powerup").text(greenatk)
    $(".pos3-2").add(".pot3-2").addClass("hpup").text(greenhp)
    $(".pos4-1").add(".pot4-1").addClass("fighter", "classpoint")
    $(".pos5-1").add(".pot5-1").addClass("hpup").text(greenhp)
    $(".pos5-2").add(".pot5-2").addClass("protectionup").text(greenpro)
    $(".pos6-1").add(".pot6-1").addClass("powerup").text(greenatk)
    $(".pos6-2").add(".pot6-2").addClass("hpup").text(greenhp)
    $(".pos7-1").add(".pot7-1").addClass("fighter", "classpoint")
    $(".pos8-1").add(".pot8-1").addClass("hpplus").text(greenhpplus)
    $(".pos8-2").add(".pot8-2").addClass("healup").text(greenheal)
    $(".pos9-1").add(".pot9-1").addClass("protectionup").text(greenpro)
    $(".pos9-2").add(".pot9-2").addClass("hpup").text(greenhp)
    $(".pos10-1").add(".pot10-1").addClass("protectionplus").text(greenproplus)
    $(".pos11-1").add(".pot11-1").addClass("powerup").text(greenatk)
    $(".pos11-2").add(".pot11-2").addClass("protectionup").text(greenpro)
    $(".pos12-1").add(".pot12-1").addClass("fighter", "classpoint")
    $(".pos13-1").add(".pot13-1").addClass("protectionup").text(greenpro)
    $(".pos13-2").add(".pot13-2").addClass("hpup").text(greenhp)
    $(".pos14-1").add(".pot14-1").addClass("hpup").text(greenhp)
    $(".pos14-2").add(".pot14-2").addClass("powerup").text(greenatk)
    $(".pos15-1").add(".pot15-1").addClass("fighter", "classpoint")
    $(".pos16-1").add(".pot16-1").addClass("powerup").text(greenatk)
    $(".pos16-2").add(".pot16-2").addClass("hpup").text(greenhp)
    $(".pos17-1").add(".pot17-1").addClass("protectionup").text(greenpro)
    $(".pos17-2").add(".pot17-2").addClass("powerup").text(greenatk)
    $(".pos18-1").add(".pot18-1").addClass("protectionup").text(greenpro)
    $(".pos19-1").add(".pot19-1").addClass("manaup").text(greenmana)
    $(".pos19-2").add(".pot19-2").addClass("critup").text(greencrit)
    $(".pos20-1").add(".pot20-1").addClass("powerplus").text(greenatkpluslast)
    // Master Class ↓
    $(".pos21-1").add(".pot21-1").addClass("masterpowerup").text(purpleatk)
    $(".pos21-2").add(".pot21-2").addClass("masterdefup").text(purpledef)
    $(".pos22-1").add(".pot22-1").addClass("masterpowerup").text(purpleatk)
    $(".pos22-2").add(".pot22-2").addClass("masterdefup").text(purpledef)
    $(".pos23-1").add(".pot23-1").addClass("masterhpup").text(purplehp)
    $(".pos24-1").add(".pot24-1").addClass("masterpowerup").text(purpleatk)
    $(".pos24-2").add(".pot24-2").addClass("masterdefup").text(purpledef)
    $(".pos25-1").add(".pot25-1").addClass("masterhpup").text(purplehp)
    $(".pos26-1").add(".pot26-1").addClass("master_fighter").text(purpleBlank)
    // Master Class ↑
} else if (acfClass == "monk") {
    $(".classPagelink").html(monkLink);
    $(".pos1-1").add(".pot1-1").addClass("monk", "classpoint")
    $(".pos2-1").add(".pot2-1").addClass("hpup").text(greenhp)
    $(".pos2-2").add(".pot2-2").addClass("protectionup").text(greenpro)
    $(".pos3-1").add(".pot3-1").addClass("protectionup").text(greenpro)
    $(".pos3-2").add(".pot3-2").addClass("powerup").text(greenatk)
    $(".pos4-1").add(".pot4-1").addClass("monk", "classpoint")
    $(".pos5-1").add(".pot5-1").addClass("powerup").text(greenatk)
    $(".pos5-2").add(".pot5-2").addClass("hpup").text(greenhp)
    $(".pos6-1").add(".pot6-1").addClass("protectionup").text(greenpro)
    $(".pos6-2").add(".pot6-2").addClass("powerup").text(greenatk)
    $(".pos7-1").add(".pot7-1").addClass("monk", "classpoint")
    $(".pos8-1").add(".pot8-1").addClass("protectionplus").text(greenproplus)
    $(".pos8-2").add(".pot8-2").addClass("hpplus").text(greenhpplus)
    $(".pos9-1").add(".pot9-1").addClass("hpup").text(greenhp)
    $(".pos9-2").add(".pot9-2").addClass("powerup").text(greenatk)
    $(".pos10-1").add(".pot10-1").addClass("critup").text(greencrit)
    $(".pos11-1").add(".pot11-1").addClass("protectionup").text(greenpro)
    $(".pos11-2").add(".pot11-2").addClass("hpup").text(greenhp)
    $(".pos12-1").add(".pot12-1").addClass("monk", "classpoint")
    $(".pos13-1").add(".pot13-1").addClass("hpup").text(greenhp)
    $(".pos13-2").add(".pot13-2").addClass("powerup").text(greenatk)
    $(".pos14-1").add(".pot14-1").addClass("powerup").text(greenatk)
    $(".pos14-2").add(".pot14-2").addClass("protectionup").text(greenpro)
    $(".pos15-1").add(".pot15-1").addClass("monk", "classpoint")
    $(".pos16-1").add(".pot16-1").addClass("protectionup").text(greenpro)
    $(".pos16-2").add(".pot16-2").addClass("powerup").text(greenatk)
    $(".pos17-1").add(".pot17-1").addClass("hpup").text(greenhp)
    $(".pos17-2").add(".pot17-2").addClass("protectionup").text(greenpro)
    $(".pos18-1").add(".pot18-1").addClass("hpup").text(greenhp)
    $(".pos19-1").add(".pot19-1").addClass("healup").text(greenheal)
    $(".pos19-2").add(".pot19-2").addClass("powerplus").text(greenatkplus)
    $(".pos20-1").add(".pot20-1").addClass("manaup").text(greenmanalast)
    // Master Class ↓
    $(".pos21-1").add(".pot21-1").addClass("masterpowerup").text(purpleatk)
    $(".pos21-2").add(".pot21-2").addClass("masterdefup").text(purpledef)
    $(".pos22-1").add(".pot22-1").addClass("masterpowerup").text(purpleatk)
    $(".pos22-2").add(".pot22-2").addClass("masterdefup").text(purpledef)
    $(".pos23-1").add(".pot23-1").addClass("masterhpup").text(purplehp)
    $(".pos24-1").add(".pot24-1").addClass("masterpowerup").text(purpleatk)
    $(".pos24-2").add(".pot24-2").addClass("masterdefup").text(purpledef)
    $(".pos25-1").add(".pot25-1").addClass("masterhpup").text(purplehp)
    $(".pos26-1").add(".pot26-1").addClass("master_fighter").text(greenatkpluslast)
    // Master Class ↑
} else if (acfClass == "paladin") {
    $(".classPagelink").html(paladinLink);
    $(".pos1-1").add(".pot1-1").addClass("paladin", "classpoint")
    $(".pos2-1").add(".pot2-1").addClass("protectionup").text(greenpro)
    $(".pos2-2").add(".pot2-2").addClass("powerup").text(greenatk)
    $(".pos3-1").add(".pot3-1").addClass("powerup").text(greenatk)
    $(".pos3-2").add(".pot3-2").addClass("hpup").text(greenhp)
    $(".pos4-1").add(".pot4-1").addClass("paladin", "classpoint")
    $(".pos5-1").add(".pot5-1").addClass("hpup").text(greenhp)
    $(".pos5-2").add(".pot5-2").addClass("protectionup").text(greenpro)
    $(".pos6-1").add(".pot6-1").addClass("powerup").text(greenatk)
    $(".pos6-2").add(".pot6-2").addClass("hpup").text(greenhp)
    $(".pos7-1").add(".pot7-1").addClass("paladin", "classpoint")
    $(".pos8-1").add(".pot8-1").addClass("hpplus").text(greenhpplus)
    $(".pos8-2").add(".pot8-2").addClass("healup").text(greenheal)
    $(".pos9-1").add(".pot9-1").addClass("protectionup").text(greenpro)
    $(".pos9-2").add(".pot9-2").addClass("hpup").text(greenhp)
    $(".pos10-1").add(".pot10-1").addClass("powerplus").text(greenatkplus)
    $(".pos11-1").add(".pot11-1").addClass("powerup").text(greenatk)
    $(".pos11-2").add(".pot11-2").addClass("protectionup").text(greenpro)
    $(".pos12-1").add(".pot12-1").addClass("paladin", "classpoint")
    $(".pos13-1").add(".pot13-1").addClass("protectionup").text(greenpro)
    $(".pos13-2").add(".pot13-2").addClass("hpup").text(greenhp)
    $(".pos14-1").add(".pot14-1").addClass("hpup").text(greenhp)
    $(".pos14-2").add(".pot14-2").addClass("powerup").text(greenatk)
    $(".pos15-1").add(".pot15-1").addClass("paladin", "classpoint")
    $(".pos16-1").add(".pot16-1").addClass("powerup").text(greenatk)
    $(".pos16-2").add(".pot16-2").addClass("hpup").text(greenhp)
    $(".pos17-1").add(".pot17-1").addClass("protectionup").text(greenpro)
    $(".pos17-2").add(".pot17-2").addClass("powerup").text(greenatk)
    $(".pos18-1").add(".pot18-1").addClass("protectionup").text(greenpro)
    $(".pos19-1").add(".pot19-1").addClass("manaup").text(greenmana)
    $(".pos19-2").add(".pot19-2").addClass("critup").text(greencrit)
    $(".pos20-1").add(".pot20-1").addClass("protectionplus").text(greenpropluslast)
    // Master Class ↓
    $(".pos21-1").add(".pot21-1").addClass("masterpowerup").text(purpleatk)
    $(".pos21-2").add(".pot21-2").addClass("masterdefup").text(purpledef)
    $(".pos22-1").add(".pot22-1").addClass("masterpowerup").text(purpleatk)
    $(".pos22-2").add(".pot22-2").addClass("masterdefup").text(purpledef)
    $(".pos23-1").add(".pot23-1").addClass("masterhpup").text(purplehp)
    $(".pos24-1").add(".pot24-1").addClass("masterpowerup").text(purpleatk)
    $(".pos24-2").add(".pot24-2").addClass("masterdefup").text(purpledef)
    $(".pos25-1").add(".pot25-1").addClass("masterhpup").text(purplehp)
    $(".pos26-1").add(".pot26-1").addClass("master_fighter").text(greenatkpluslast)
    // Master Class ↑
} else if (acfClass == "rogue") {
    $(".classPagelink").html(rogueLink);
    $(".pos1-1").add(".pot1-1").addClass("rogue", "classpoint")
    $(".pos2-1").add(".pot2-1").addClass("powerup").text(greenatk)
    $(".pos2-2").add(".pot2-2").addClass("hpup").text(greenhp)
    $(".pos3-1").add(".pot3-1").addClass("hpup").text(greenhp)
    $(".pos3-2").add(".pot3-2").addClass("protectionup").text(greenpro)
    $(".pos4-1").add(".pot4-1").addClass("rogue", "classpoint")
    $(".pos5-1").add(".pot5-1").addClass("protectionup").text(greenpro)
    $(".pos5-2").add(".pot5-2").addClass("powerup").text(greenatk)
    $(".pos6-1").add(".pot6-1").addClass("hpup").text(greenhp)
    $(".pos6-2").add(".pot6-2").addClass("protectionup").text(greenpro)
    $(".pos7-1").add(".pot7-1").addClass("rogue", "classpoint")
    $(".pos8-1").add(".pot8-1").addClass("hpplus").text(greenhpplus)
    $(".pos8-2").add(".pot8-2").addClass("manaup").text(greenmana)
    $(".pos9-1").add(".pot9-1").addClass("powerup").text(greenatk)
    $(".pos9-2").add(".pot9-2").addClass("protectionup").text(greenpro)
    $(".pos10-1").add(".pot10-1").addClass("powerplus").text(greenatkplus)
    $(".pos11-1").add(".pot11-1").addClass("hpup").text(greenhp)
    $(".pos11-2").add(".pot11-2").addClass("powerup").text(greenatk)
    $(".pos12-1").add(".pot12-1").addClass("rogue", "classpoint")
    $(".pos13-1").add(".pot13-1").addClass("powerup").text(greenatk)
    $(".pos13-2").add(".pot13-2").addClass("protectionup").text(greenpro)
    $(".pos14-1").add(".pot14-1").addClass("protectionup").text(greenpro)
    $(".pos14-2").add(".pot14-2").addClass("hpup").text(greenhp)
    $(".pos15-1").add(".pot15-1").addClass("rogue", "classpoint")
    $(".pos16-1").add(".pot16-1").addClass("hpup").text(greenhp)
    $(".pos16-2").add(".pot16-2").addClass("protectionup").text(greenpro)
    $(".pos17-1").add(".pot17-1").addClass("powerup").text(greenatk)
    $(".pos17-2").add(".pot17-2").addClass("hpup").text(greenhp)
    $(".pos18-1").add(".pot18-1").addClass("powerup").text(greenatk)
    $(".pos19-1").add(".pot19-1").addClass("protectionplus").text(greenproplus)
    $(".pos19-2").add(".pot19-2").addClass("healup").text(greenheal)
    $(".pos20-1").add(".pot20-1").addClass("critup").text(greencritlast)
    // Master Class ↓
    $(".pos21-1").add(".pot21-1").addClass("masterpowerup").text(purpleatk)
    $(".pos21-2").add(".pot21-2").addClass("masterdefup").text(purpledef)
    $(".pos22-1").add(".pot22-1").addClass("masterpowerup").text(purpleatk)
    $(".pos22-2").add(".pot22-2").addClass("masterdefup").text(purpledef)
    $(".pos23-1").add(".pot23-1").addClass("masterhpup").text(purplehp)
    $(".pos24-1").add(".pot24-1").addClass("masterpowerup").text(purpleatk)
    $(".pos24-2").add(".pot24-2").addClass("masterdefup").text(purpledef)
    $(".pos25-1").add(".pot25-1").addClass("masterhpup").text(purplehp)
    $(".pos26-1").add(".pot26-1").addClass("master_fighter").text(greenatkpluslast)
    // Master Class ↑
} else if (acfClass == "wizard") {
    $(".classPagelink").html(wizardLink);
    $(".pos1-1").add(".pot1-1").addClass("wizard", "classpoint")
    $(".pos2-1").add(".pot2-1").addClass("powerup").text(greenatk)
    $(".pos2-2").add(".pot2-2").addClass("protectionup").text(greenpro)
    $(".pos3-1").add(".pot3-1").addClass("protectionup").text(greenpro)
    $(".pos3-2").add(".pot3-2").addClass("hpup").text(greenhp)
    $(".pos4-1").add(".pot4-1").addClass("wizard", "classpoint")
    $(".pos5-1").add(".pot5-1").addClass("hpup").text(greenhp)
    $(".pos5-2").add(".pot5-2").addClass("powerup").text(greenatk)
    $(".pos6-1").add(".pot6-1").addClass("protectionup").text(greenpro)
    $(".pos6-2").add(".pot6-2").addClass("hpup").text(greenhp)
    $(".pos7-1").add(".pot7-1").addClass("wizard", "classpoint")
    $(".pos8-1").add(".pot8-1").addClass("hpplus").text(greenhpplus)
    $(".pos8-2").add(".pot8-2").addClass("protectionplus").text(greenproplus)
    $(".pos9-1").add(".pot9-1").addClass("powerup").text(greenatk)
    $(".pos9-2").add(".pot9-2").addClass("hpup").text(greenhp)
    $(".pos10-1").add(".pot10-1").addClass("critup").text(greencrit)
    $(".pos11-1").add(".pot11-1").addClass("protectionup").text(greenpro)
    $(".pos11-2").add(".pot11-2").addClass("powerup").text(greenatk)
    $(".pos12-1").add(".pot12-1").addClass("wizard", "classpoint")
    $(".pos13-1").add(".pot13-1").addClass("powerup").text(greenatk)
    $(".pos13-2").add(".pot13-2").addClass("hpup").text(greenhp)
    $(".pos14-1").add(".pot14-1").addClass("hpup").text(greenhp)
    $(".pos14-2").add(".pot14-2").addClass("protectionup").text(greenpro)
    $(".pos15-1").add(".pot15-1").addClass("wizard", "classpoint")
    $(".pos16-1").add(".pot16-1").addClass("protectionup").text(greenpro)
    $(".pos16-2").add(".pot16-2").addClass("hpup").text(greenhp)
    $(".pos17-1").add(".pot17-1").addClass("powerup").text(greenatk)
    $(".pos17-2").add(".pot17-2").addClass("protectionup").text(greenpro)
    $(".pos18-1").add(".pot18-1").addClass("powerup").text(greenatk)
    $(".pos19-1").add(".pot19-1").addClass("healup").text(greenheal)
    $(".pos19-2").add(".pot19-2").addClass("manaup").text(greenmana)
    $(".pos20-1").add(".pot20-1").addClass("powerplus").text(greenatkpluslast)
    // Master Class ↓
    $(".pos21-1").add(".pot21-1").addClass("masterpowerup").text(purpleatk)
    $(".pos21-2").add(".pot21-2").addClass("masterdefup").text(purpledef)
    $(".pos22-1").add(".pot22-1").addClass("masterpowerup").text(purpleatk)
    $(".pos22-2").add(".pot22-2").addClass("masterdefup").text(purpledef)
    $(".pos23-1").add(".pot23-1").addClass("masterhpup").text(purplehp)
    $(".pos24-1").add(".pot24-1").addClass("masterpowerup").text(purpleatk)
    $(".pos24-2").add(".pot24-2").addClass("masterdefup").text(purpledef)
    $(".pos25-1").add(".pot25-1").addClass("masterhpup").text(purplehp)
    $(".pos26-1").add(".pot26-1").addClass("master_fighter").text(greenatkpluslast)
    // Master Class ↑
} // End of Hero class loading
